version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:12
      - image: linuxserver/qbittorrent
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm ci
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: test
          command: |
            ./cc-test-reporter before-build
            npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: './reports'
            JEST_JUNIT_OUTPUT_NAME: 'test-results.xml'
      - store_test_results:
          path: ./reports
      - run:
          name: lint
          command: npm run lint
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: codecov
          command: ./cc-test-reporter after-build
  release:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - test
